### PR TITLE
Fix uispecs not saving screenshots on buddybuild

### LINKED ISSUE #672: After scheme split uitests screenshots aren't captured
I think I broke the screenshotting feature at #642 

You can see screenshots on build 1996 but not since 2011. My bad. 😔 

FYI for @isabelrios but I'll look at this since I was the one who touched the schemes last

### PR DESCRIPTION
**Pull request by isabelrios**
Tries to resolve #672 🤞 
Lets try to create the screenshots folder as part as the post-action build steps so that they can be stored there...

### CODE REVIEW

**Comment by isabelrios** [comment]
Yeah, also for me...lets see if it works there too... 🙈

**Comment by devinreams** [comment]
Build 2181 did not save (didn't even really show its attempts to) any screenshots.

Build 2191 seems to do the same.

Ughhh I don't understand you fastlane + buddybuild...

**Comment by isabelrios** [comment]
:woman-facepalming: I will investigate further and try to get it working here...

**Comment by devinreams** [comment]
I'm wondering out loud (and couldn't tell in the docs) if the user home directory is where buddybuild throws fastlane's screenshot assets.

I presume its "just another Mac" and works the same as locally but when downloading the logs from buddybuild I can't see anything in the home dir beyond the git checkout/repo...

That's as far as I got in my spare ~30 minutes today. 😔

**Comment by isabelrios** [comment]
I may be wrong, but I think this is half fixed, at least the error is not shown in the logs and the snapshots are working again...

See this logs where the error is seen (master, test0): 
https://dashboard.buddybuild.com/apps/5a0ddb736e19370001034f85/build/5b983f36a2a3ad0001bc5234/test/6030762d-221f-4661-a88e-53a54b42b39e/2bf81d19-cba3-415d-a922-127e1e002d9f

And in this branch:
https://dashboard.buddybuild.com/apps/5a0ddb736e19370001034f85/build/5b98fc55accf7b0001f384da/test/ad76019f-0589-4fb2-8b4a-4422fd8967e3/63fe30d6-cbff-49f1-b1e6-deca8a8358f2

You can see `snapshot: 02EntryListUICTContentSizeCategoryL` instead of the previous error.

But, on BB the screenshots are not shown yet 😣 I will ask them in case they have any clue about this...

**Comment by devinreams** [comment]
>the error is not shown in the logs and the snapshots are working again..

Yay! Thanks @isabelrios 

>on BB the screenshots are not shown yet

OK I'm still stumped by that too because there used to be placeholder (but broken) screenshots showing. But now I can't even find a build on any branch with that happening. 😫

Thanks for contacting buddybuild, good idea 👍

**Comment by isabelrios** [comment]
> But now I can't even find a build on any branch with that happening. 😫


Yes, it is really strange, the broken screenshot are shown, you can find them here for example, on this branch when I forced a failure (wait a little bit until they are loaded):
https://dashboard.buddybuild.com/apps/5a0ddb736e19370001034f85/build/5b9900396425650001d112bc/test/ed230278-4cd8-4531-ac54-2d63634474f0/69137a3a-2e3c-4a9a-9f7d-5a05477fba6a

They are only shown on failures....

> Thanks for contacting buddybuild

I have not heard back from them, will let you know

**Comment by devinreams** [comment]
@isabelrios ok this was re-run against Xcode 10 GM and the failure is missing images so you can show buddybuild:
https://dashboard.buddybuild.com/apps/5a0ddb736e19370001034f85/build/5b9aaf68cdb471000106a3fe/test/57720845-7b0c-46e7-ac64-ab9671e4ce5d/6523a9be-118d-42b8-a7b6-c71f1783a3a9

**Comment by isabelrios** [comment]
> @isabelrios ok this was re-run against Xcode 10 GM and the failure is missing images so you can show buddybuild

I was talking to them yesterday afternoon to show them builds with screenshots and with the broken ones, I was forcing some of my branches to fail so that there were screenshots as we see them now . The guy checked a build as it was running and said that he has to  investigate deeply and check with his colleagues, as at that moment he did not know where the problem could be. Hopefully I will hear back from him today, if not I will ping him. :)

**Comment by isabelrios** [comment]
@devinreams I finally heard back from BB:

> We are currently working on a resolution for this problem.
> Thanks for your patience in this process. I'll let you know when it's resolved.

So, once the snapshots are already working, there is nothing else we can do, looks like it is an issue on their side. We are experiencing the same on firefox-ios builds :(

**Comment by isabelrios** [comment]
Looks like we have screenshots again on BB! 
https://dashboard.buddybuild.com/apps/5a0ddb736e19370001034f85/build/5b9aaf68cdb471000106a3fe/test/57720845-7b0c-46e7-ac64-ab9671e4ce5d/6523a9be-118d-42b8-a7b6-c71f1783a3a9

But we would still need this PR to fix the snapshot issue...in other branches the original problem `Problem writing screenshot: ...` is still seen.

**Pull request merged**
