### PR TITLE
fix specs firefox_lockbox

### PR DESCRIPTION
**Pull request by sashei**
Follow up to #322

### CODE REVIEW

**Comment by devinreams** [comment]
Ugh, I'm super curious as to why these tests didn't fail before landing on master...

**Comment by sashei** [comment]
me too! I went & checked out the BB history & everything, very strange.

**Comment by sashei** [comment]
actually, I think the branches run against the branch target, which you left with the module name Lockbox..... that would make sense.

**Comment by sashei** [comment]
...wait, this means that all the _branches_ will fail with my change here. I think we need them to be unified if we want specs to build on both branches & release builds.

**Comment by devinreams** [comment]
>you left with the module name Lockbox
>we need them to be unified if we want specs to build on both branches & release builds

Oh neat. I see...

I can't quite tell where to make changes to unify. Does it have to do with the product names?

https://github.com/mozilla-lockbox/lockbox-ios/blob/f1c6662fe551284185a076ce5bae79d481aece49/Lockbox.xcodeproj/project.pbxproj#L1571-L1606

**Comment by devinreams** [comment]
>fix module declaration instead

OIC. Sorry, I knew I was going to unexpectedly cause a problem here. 😔

**Pull request merged**
