### PR TITLE
Adjust integration

### LINKED ISSUE #608: Integrate Adjust for marketing tracking
Lockbox iOS token: 383z4i46o48w

Integrate the Adjust SDK doc: https://docs.adjust.com/en/getting-started/#integrate-the-adjust-sdk

and github repo: https://github.com/adjust/ios_sdk

Add events: https://github.com/adjust/ios_sdk#event-tracking

I think the todos here are:
- [X] Product to define the key events that we want marketing to track (anything more than attribution?) - no specific events to track with Adjust at this time.
~- [ ] Marketing to create new event(s) in the Adjust dashboard~
- [X] Lockbox engineering to integrate the Adjust SDK
~- [ ] Lockbox engineering to update app code with Adjust events~

### PR DESCRIPTION
**Pull request by joeyg**
Sets up adjust, resolves #608

### CODE REVIEW

**Comment by devinreams** [comment]
Thanks for adding that, @joeyg.

@sandysage @sashei what do you think: should we mark this WIP until we have everything squared away at #608? Or merge this now to get the code integrated? I learn towards the former...

**Comment by sashei** [comment]
former sounds good to me.

**Comment by devinreams** [comment]
This is no longer WIP as nothing else is needed (beyond code and sanity review).

**Comment by joeyg** [comment]
@devinreams let me know if the events are not showing up on the dashboard or if the data sharing setting is not being respected

**Comment by sashei** [comment]
@joeyg thanks for the contribution!! 🌻

**Comment by devinreams** [comment]
@sandysage are you able to pull down this build and run it and see if the events show up in Adjust (or work with the folks that monitor it) before we merge this?

I'm not entirely clear on what ya'll are looking for but will help test this end-to-end at your convenience..

**Comment by sandysage** [comment]
Confirmed with marketing that this is showing. I don't currently have access, but based on that update I think this is good to go.

**Comment by linuxwolf** [comment]
hey @joeyg the merge conflict looks pretty simple; ok to do it in-place or is there anything you want a last look at beforehand?

**Comment by joeyg** [comment]
@linuxwolf - Yeah - it was a small conflict so I resolved it on GitHub - if the builds fail then I'll pull it down and look into it.

**Comment by devinreams** [comment]
Thanks again for this @joeyg (and @sashei and @linuxwolf for the `master` merges).

@sandysage can you please reach out to the proper folks again just to make super sure this recording for them? I will pull a build onto my iPhone X and make sure it has some data.

**Pull request merged**
