### PR TITLE
Initial release notes and release preparation instructions

### LINKED ISSUE #125: Create a Test Flight build (Beta releases)
Blocked by #211

### LINKED ISSUE #268: Prepare iTunes Connect for external testers via TestFlight
https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/ng/app/1314000270/testflight?section=testinformation

- [ ] Beta App Description
  - Provide a description of your app that highlights its features and functionality.
- [x] Review Notes
  - Additional information about your app that can help during the review process. Do not include demo account details. Review notes can’t exceed 4000 characters.
- [ ] License Agreement
- [x] Marketing URL: https://lockbox.firefox.com/
- [x] Privacy Policy URL: https://mozilla-lockbox.github.io/lockbox-ios/metrics/
- [x] "Sign-In Information" (FxA account) for tester: `dreams+appletester@mozilla.com`

The items already provided above seem to have satisfied Apple's requirements for TestFlight for external users (the ⚠️ warning icon went away) but will keep this open for tracking and to revisit as we get closer to launch.

### PR DESCRIPTION
**Pull request by devinreams**
Resolves #268 
Resolves #125

A quick first pass at jotting down thoughts since getting things wired up through buddybuild to iTunes Connect and TestFlight.

@sashei can you think of more you'd like to add? or anything I should flesh out in more detail so this is less cryptic?

### CODE REVIEW

**Comment by sashei** [comment]
@devinreams actually thinking about it, I think there is a distinction between `internal` and `external` testers in TestFlight that isn't addressed here. Do we want to distribute internally before we send the app to Beta review? Or do we want to just let Apple do that for us / expect to catch things in BuddyBuild distributions?

**Comment by devinreams** [comment]
> I think there is a distinction between internal and external testers in TestFlight that isn't addressed here

Good point. Words are tough... I added more context and a link to Apple's own description.

>Do we want to distribute internally before we send the app to Beta review?

Yes, we will be opening up a sign up form for "internal (Mozilla) external (TestFlight) users" via the tldr this week.

I've also been offering (and told @sandysage) to add anyone who asks for access...

---

And because I love visuals and 2x2 grids:

blank

**Comment by joeyg** [comment]
@devinreams Curious why there is no plan to use Testflight for external testing? Firefox and Focus both use it prior to their releases.

**Comment by sandysage** [comment]
@joeyg For this initial release, we're relying on [Test Pilot](https://testpilot.firefox.com/) for early testing, which requires access to a 'live' app given the sheer number of potential users.

Our longer term plans may include more incremental Beta updates for external-to-Mozilla testers. But right now we're focused on launching to Test Pilot first.

**Pull request merged**
