### PR TITLE
Latest copy and content updates

### LINKED ISSUE #272: Font Weight on Header Buttons
Use SF Regular for Action buttons instead of Semibold/Bold. 

For any text buttons in the header bar, let's use a regular font weight instead of a bolder one...

Back buttons (for settings and entry details) appear to be correct, but 'Cancel' and 'Done' appear to be bolder.

### LINKED ISSUE #305: Content updates across app
Some updates to content across the app now that the content team has had the opportunity to do their review.

#### Settings > Account
**InVision**
Account: https://mozilla.invisionapp.com/share/7JEUG47ZU#/268019832_Settings_-_Account
Account - Unlink Confirmation: https://mozilla.invisionapp.com/share/7JEUG47ZU#/268020745_Settings_-_Account_-_Unlink
**Zeplin**
Account: https://zpl.io/a7ZMgyE
Account - Unlink Confirmation: https://zpl.io/2GzN1j9

- [x] Body copy: “To make changes to your account, log in to your Firefox Account from any browser.”
- [x] Unlink account button: "Clear out Lockbox"
- [x] Unlink account button description: "This will remove any synced entries from Lockbox, but will not delete your account or entries from Firefox."
- [x] Unlink account dialog/modal:
Title: "Clear out Lockbox?"
Subtitle: "This will delete your Firefox Account information and all saved entries from Lockbox."

<br/>

#### Legal
- ~Any instances where we have Lockbox, change to Firefox Lockbox~ moving to separate issue

<br/>

#### Auto Lock
**InVision**
https://mozilla.invisionapp.com/share/7JEUG47ZU#/267560622_Settings_-_Auto_Lock
**Zeplin**
https://zpl.io/bAGeO9o

- [x] Table heading: “Sign out of Lockbox after”

<br/>

#### Entry Detail
**InVision**
Entry Detail: https://mozilla.invisionapp.com/share/7JEUG47ZU#/267560603_Entry_Detail
Entry Detail (Tutorial Username): https://mozilla.invisionapp.com/share/7JEUG47ZU#/268014045_Entry_Detail_-_Onboarding_-_Username
Entry Detail (Tutorial Password): https://mozilla.invisionapp.com/share/7JEUG47ZU#/268014046_Entry_Detail_-_Onboarding_-_Password
**Zeplin**
Entry Detail: https://zpl.io/VK4vXDX
Entry Detail (Tutorial Username): https://zpl.io/an1Ejyn
Entry Detail (Tutorial Password): https://zpl.io/adAAYd5

- [x] Copy dialog/modal for Username: “Username copied”
- [x] Copy dialog/modal for Password: “Password copied”
- [x] Edit disclaimer at bottom: “Learn how to edit this entry [chevron-right]”

<br/>

@devinreams moved biometrics to https://github.com/mozilla-lockbox/lockbox-ios/issues/321

### PR DESCRIPTION
**Pull request by devinreams**
Fixes #305 
Fixes #272 

## Settings > Account

screen shot 2018-05-01 at 1 58 50 pm
screen shot 2018-05-01 at 1 58 54 pm

## Settings > Auto Lock

screen shot 2018-05-01 at 2 32 20 pm

## Cancel / Done nav buttons

screen shot 2018-05-01 at 2 32 20 pm
screen shot 2018-05-01 at 2 34 23 pm

---

After looking at the in progress work I will split the biometrics copy updates off into a separate issue.

I also suggest we revisit the "Firefox Lockbox" rename and explicitly call out which instances of "Lockbox" should be replaced.

### CODE REVIEW

**Comment by changecourse** [comment]
@devinreams one thing we didn't catch prior... on the unlink dialog, let's change the button to a blue 'Confirm' instead.

https://mozilla.invisionapp.com/share/7JEUG47ZU#/268020745_Settings_-_Account_-_Unlink

**Comment by devinreams** [comment]
> one thing we didn't catch prior... on the unlink dialog, let's change the button to a blue 'Confirm' instead.

For what it's worth, the style currently applied is the Apple-provided "destructive" which seems to be most appropriate for confirmation of a destructive action: https://developer.apple.com/documentation/uikit/uialertactionstyle

>default: Apply the default style to the action’s button. 
>cancel: Apply a style that indicates the action cancels the operation and leaves things unchanged.
>destructive: Apply a style that indicates the action might change or delete data.

If we were to change the "Cancel" button to use "Cancel" style and the "Unlink" to have the default style, you would see iOS 11 make the former appear bold and the later not. 

@mozilla-lockbox/ux I suggest we stick to Apple's provided styles (destructive for Unlink, cancel for Cancel). Would you agree?

**Comment by nickbrandt** [comment]
@devinreams I think that makes sense. This was a change we made based on the copy changing from mentioning "unlink" anywhere in the descriptions. We wanted the action to be clear to the user as to what the action was doing, but didn't really want something long like "Clear out Firefox Lockbox". Maybe we do as you suggested (stick with "cancel" and "destructive" styles), but update the action to "Clear Out"? Unless we think it should just remain "Unlink". @changecourse thoughts?

**Comment by devinreams** [comment]
>We wanted the action to be clear to the user as to what the action was doing, but didn't really want something long like "Clear out Firefox Lockbox". Maybe we do as you suggested (stick with "cancel" and "destructive" styles), but update the action to "Clear Out"? Unless we think it should just remain "Unlink".

Ah yes, I meant to say: what if we changed the "Unlink" button to just say "Clear" (in the red destructive style)?

"Reset" also felt like a common verb folks use in situations like this...

**Comment by nickbrandt** [comment]
I like "Clear" in this instance, as it seems like the appropriate action for the "Clear out your Firefox Lockbox?" question. I say we go with that 👍

**Comment by devinreams** [comment]
>I like "Clear" in this instance

Cool. Here's what it all looks like now:

screen shot 2018-05-02 at 3 27 56 pm

@mozilla-lockbox/ux can you please review the latest build once its available and provide your final review here (approval/changes requested) accordingly? 😁

**Comment by nickbrandt** [comment]
@devinreams I also find it amusing how Apple doesn't even follow their own guidelines (in regards to the dialog button conversation)

apple-1
apple-2

**Comment by devinreams** [comment]
>the disclaimer at the bottom of Entry Details page. Is the plan to hold off on this one until we have the URL available for the link to FAQ?

Is that link now the same as #172?

>Not sure if the height of those copy dialogs is hard coded or something, but it appears to be the same height as when it went to two lines (so more padding on bottom now).

I'll check that out 👍 

>I also find it amusing how Apple doesn't even follow their own guidelines 

Ah yes, the fun differences between what Apple builds themselves (across multiple teams, even so) vs. provides to app developers. 🤷‍♂️

**Comment by nickbrandt** [comment]
> Is that link now the same as #172?

@devinreams Ah yes, right. My bad I just saw that checked off and didn't see the changes, but you're right that will be covered in #172 (which has designs updated). Thanks!

**Comment by devinreams** [comment]
>My bad I just saw that checked off and didn't see the changes

Oh no I may have checked it but then forgot, then remembered why I skipped it, my bad entirely.

>Not sure if the height of those copy dialogs is hard coded or something, but it appears to be the same height as when it went to two lines

I found it's a percentage (40%) of the view height. I'm having a hard time getting my test data loading in so I'm gonna drop it down to 30% and push here to see how it looks...

**Comment by devinreams** [comment]
OK the "copied" alert and text blurb at the bottom are updated.

The blurb is mostly placeholder to finish up at #172...

img_2827

**Pull request merged**
