### PR TITLE
iPad: launch and welcome screens

### PR DESCRIPTION
**Pull request by joeyg**
Depends on #838

Connected to #745 

## Testing and Review Notes
 * Won't have a build to test until #838 lands (with fixed tests)
 * iPhone launch screen should remain unchanged
 * iPad should work in portrait and landscape
 * Welcome screen and launch screen should work

## Screenshots or Videos
iPhone 8:
simulator screen shot - iphone 8 - 2019-01-04 at 20 50 45

simulator screen shot - iphone 8 - 2019-01-05 at 21 25 40

iPad Pro 12 9-inch Landscape
simulator screen shot - ipad pro 12 9-inch - 2019-01-04 at 20 50 05

simulator screen shot - ipad pro 12 9-inch - 2019-01-05 at 21 24 14

iPad Pro 12 9-inch Portrait
simulator screen shot - ipad pro 12 9-inch - 2019-01-04 at 20 49 44

simulator screen shot - ipad pro 12 9-inch - 2019-01-05 at 21 24 31

### CODE REVIEW

**Comment by joeyg** [comment]
@nickbrandt When I use the nessie.png and nessie@2x.png files from Zeplin the landscape screen doesn't look right for the 12.9" iPad:

simulator screen shot - ipad pro 12 9-inch - 2019-01-09 at 20 45 55

Is there a way to make those images a bit longer?

**Comment by joeyg** [comment]
> Build 2798 worked for me and looked as expected on an iPad Pro in portrait mode. But rotated into landscape now the alignment of the image and background seem off:

@devinreams Yep - @nickbrandt said that he will be able to create a new asset with a longer grey area to help fix that issue. Thanks for testing.

**Comment by changecourse** [comment]
@devinreams I believe we owe @joeyg a larger wave/creature image to support the iPad Pro landscape resolution. I'll coordinate this with @nickbrandt and provide the image on this issue soon!

**Comment by nickbrandt** [comment]
@joeyg here is the nessie image that has been updated to fit the 12.9" iPad Pro. Let me know if you need anything else!

[nessie.zip](https://github.com/mozilla-lockbox/lockbox-ios/files/2760710/nessie.zip)

**Comment by joeyg** [comment]
Thanks @nickbrandt! New screenshots of launch screen and welcome screen on 12.9" iPad Pro.

simulator screen shot - ipad pro 12 9-inch 3rd generation - 2019-01-15 at 12 09 08
simulator screen shot - ipad pro 12 9-inch 3rd generation - 2019-01-15 at 12 09 11

simulator screen shot - ipad pro 12 9-inch 3rd generation - 2019-01-15 at 12 09 21
simulator screen shot - ipad pro 12 9-inch 3rd generation - 2019-01-15 at 12 09 24

**Pull request merged**
