### PR TITLE
XCUITests improvements

### LINKED ISSUE #686: XCUITests: some improvements
This is a first step until we get issue #531 working. Making all GET/PUT requests which work async to work synchronously as @jhugman suggested will require a big refactor of the tests. I will work on that but lets do a little bit of work first to keep the tests updated while the other work is being done.

So, the idea is to update the tests that had comments from the change to OAuth flow and move the methods to ScreenGraph so that the test suite is more readable.
Also, a new basic test to check the App version can be added

Depends on #639

### PR DESCRIPTION
**Pull request by isabelrios**
Resolves #686 
As commented in the issue, before doing all the big refactor to have all the calls working Synchronously and so make the tests working independently, lets do a little bit of clean up for having the tests ready for the new implementations coming to master. 
Lets remove the commented tests, add methods to ScreenGraph so the test suite is more easy to read/maintain, and add a new test for checking that the app version is shown

### CODE REVIEW

**Comment by devinreams** [comment]
I'm going to point this PR to the `autofill` branch and see how it builds.

@sashei would you rather this land first or after the `autofill` branch work?

**Comment by sashei** [comment]
the less we have to rebase the autofill branch, the better, so I'm going to say after....

**Comment by isabelrios** [comment]
Oh no worries, thanks for the help here :)! I will check if there are conflicts or tests failing and fix them.

**Comment by devinreams** [comment]
Oddly enough the buddybuild simulator is failing on test 6 on this branch right now. But it _sometimes_ passes fine on buddybuild. And always passes locally (for me).

>Assertion Failure: LockboxXCUITests.swift:176: XCTAssertEqual failed: ("Select options for sorting your list of entries (currently A-Z)") is not equal to ("Select options for sorting your list of entries (currently Recent)")

https://dashboard.buddybuild.com/apps/5a0ddb736e19370001034f85/build/5b980d8cb950ad0001815b5b#logs

I kicked it off one more time just to see what happens. What do you think @isabelrios? Merge as-is or disable it temporarily? 🙃

**Comment by isabelrios** [comment]
As a workaround I have tried to do the test steps one by one, clicking on each button directly in the test, instead of using the Screengraph. The test passed once, I will run it again and if it is green and you agree we can land it with this solution until it works on bb too using the Screengraph. If it fails, then I will disable here, no need to add noise and intermittents failures to master...

**Comment by devinreams** [comment]
>I have tried to do the test steps one by one, clicking on each button directly in the test, instead of using the Screengraph

That seems to have done the trick! Thank you, @isabelrios 🙇 🥇 

I will merge this in momentarily...

**Pull request merged**
