### PR TITLE
enable without infinite spin when no logins

### LINKED ISSUE #737: Attempting to enable AutoFill with a Firefox Account with no credentials spins forever
If you have an account with no synced logins (dreams+appletester) then go to Settings > Passwords > AutoFill > Enable the enable screen seems to spin infinitely.

### PR DESCRIPTION
**Pull request by sashei**
resolves #737

### CODE REVIEW

**Comment by joeyg** [comment]
@devinreams Tested this out in the simulator with an account without credentials and it worked fine: https://drive.google.com/open?id=13EzNJWdpcjWPi3Qgc1dHhZ49At-OO9O0

**Comment by devinreams** [comment]
I admit I wasn't super thorough and a full pass back through the test plan would make most sense to make sure the happy path isn't the only thing touched: https://github.com/mozilla-lockbox/lockbox-ios/blob/master/docs/test-plan-autofill.md

**Comment by joeyg** [comment]
Verified test cases: 2, 3, 5 - will do the others on device.

**Comment by sashei** [comment]
very stale, doesn't work

**Pull request closed without merging**
