### PR TITLE
accessibility IDs

### LINKED ISSUE #471: Add more accessibilityIdentifier's
From @isabelrios https://github.com/mozilla-lockbox/lockbox-ios/issues/453#issuecomment-393860114

>The accessibility Label part is fixed, almost all items have one, but not the accessibilityIdentifier. There are only a few. I added new ones in #303 but still there are more missing...and for some of them I would need devs help, not sure how to do it...

Good call-out, thanks @isabelrios. We can help get those added. (and by we I mean @sashei and maybe me if I did a little more reading)

### Welcome

- [x] "Get Started" = getStarted.button in #453
- [x] Learn More button = learnMore.button in #479

### Items List

- [x] A-Z / Recency sort button = sorting.button in #453
- [X] Settings gear button = settings.button in #453
- [x] Search/filter field = filterEntries.textField  in #479
- [ ] Clear filter button
- [x] Cancel filter button = cancelFilterTextEntry.button in #479
- [x] No entries learn more button = learnMore.button in #479

### Item Detail

- [ ] Web address label/row
- [ ] Username label/row
- [ ] Password label/row
- [x] Show/Hide password button = reveal.button in #453
- [x] Learn more button = learnEditEntry.button in #453

### Settings List

- [ ] Send Feedback button/row
- [ ] FAQ button/row
- [x] Send Usage Data switch toggle = sendUsageData.switch in #453
- [ ] FxA "Account" settings button/row
- [ ] Auto Lock button/row
  - [ ] Auto Lock options/rows in view
- [ ] Open Websites In button/row
  - [ ] Browser options/rows in view
- [x] Lock Now button/row = lockNow.button in #453

#### Account Settings

- [x] User name = userName.label in #453
- [x] Disconnect button = disconnectFirefoxLockbox.button in #479
  - [ ] Cancel confirm button
  - [ ] Disconnect confirm button

### Lock Screen

- [x] Unlock button = biometrics.button in #479

### PR DESCRIPTION
**Pull request by sashei**
resolves #471

### CODE REVIEW

**Comment by sashei** [comment]
@devinreams I think @isabelrios was just using the text from the cell on some of those rather than the accessibilityIDs in the xcuitests that I looked at, but I could be wrong.

**Comment by isabelrios** [comment]
Hi @sashei @devinreams For some navigations bars and buttons I'm using acc.ID added in LockboxScreenGraph (for those all I could add), for what I'm using labels is for options in Settings, for those options I was not able to add the acc.ID (like "Open Websites in"). 
Hope this helps to clarify, if not please let me know.
Thanks!

**Comment by devinreams** [comment]
>what I'm using labels is for options in Settings, for those options I was not able to add the acc.ID

@isabelrios Aha. So when looking at this PR, does this provide as much as you needed/desired to have as we outlined at #471? Or do you expect any more items to have IDs?

**Comment by isabelrios** [comment]
It would be nice if there are at least IDs for the missing items under **Setting List**:
- [ ] Send Feedback button/row
- [ ] FAQ button/row
- [ ] FxA "Account" settings button/row
- [ ] Auto Lock button/row
- [ ] Open Websites In button/row


For the ones under **Item Detail**:
- [ ] Username label/row
- [ ] Password label/row

And for the two buttons under **Sort Entries** menu:
- [ ] Alphabetically
- [ ] Recently Used

With that all the tests will work although there are changes in the Labels due to changes on those Strings.

But if you want to do this in a follow up PR, that's fine for me, as long as they are added at some point :)
Thanks!

**Comment by sashei** [comment]
The settings & item detail accessibility IDs are pretty trivial; the `Alphabetically` and `Recently Used` option sheet requires some private API accessing / hackery so I didn't add those for now.

**Comment by isabelrios** [comment]
Thanks @sashei! And sorry for my ignorance when trying to add those.
It's fine for me to leave the Alphabetically and Recently Used ones for the future

**Comment by sashei** [comment]
@isabelrios no worries!! The way we're doing tableview layouts is non-standard so I can imagine it's hard to surface looking at the code. Hope these are helpful, and thanks for the r+ !!

**Pull request merged**
