### PR TITLE
re-add biometric unlock button

### LINKED ISSUE #343: Add back Face/Finger ID button to Welcome screen to re-prompt and unlock
Removed at #314. 

See also #384 

Consider adding the button to unlock back to Welcome screen so users that cancel the dialog/prompt can re-authenticate and unlock without closing/reopening the app.

Assets and (unused strings) are still in there.

Flagging as MVP candidate to consider...

- add Face/Finger button/icon
- add text beneath button

## Visual Design
**InVision**
Touch ID: https://mozilla.invisionapp.com/share/7JEUG47ZU#/screens/288717368
Face ID: https://mozilla.invisionapp.com/share/7JEUG47ZU#/screens/267560535

**Zeplin**
Touch ID: https://zpl.io/V0ZW5xO
Face ID: https://zpl.io/aRNL9Ln

### PR DESCRIPTION
**Pull request by sashei**
resolves #343

### CODE REVIEW

**Comment by sashei** [comment]
One question that I had (maybe @changecourse @nickbrandt have thoughts
here): what should the icon / label text say if the user doesn't have
biometrics but does have device authentication? there's no PIN image /
equivalent for the button in this story. Right now I think it will just
display the touch ID prompt in that scenario.

**Comment by sashei** [comment]
@nickbrandt love it! I will update the press states and copy. For some reason, the lock is not downloading from Zeplin properly? It's just blank when I go to export it.

**Comment by nickbrandt** [comment]
@sashei sorry, that was my mistake. Here's the icon:

[icon-unlock.zip](https://github.com/mozilla-lockbox/lockbox-ios/files/2058730/icon-unlock.zip)

**Comment by sashei** [comment]
@nickbrandt @devinreams @mozilla-lockbox/mobile-engineering this is ready for re-review!

**Comment by nickbrandt** [comment]
@sashei Looks great! Thanks for making those changes 👍

**Pull request merged**
