### PR TITLE
Display the settings button on iOS10 + small screens

### LINKED ISSUE #278: Settings button not displayed on iOS 10.3
master 614cc5c9
iPhone SE/iPhone 6 (iOS 10.3.3)

1. Install Lockbox. 
2. Login with a valid account.

Expected: The "Settings" button should be displayed in the top-right corner.

Actual: The button is not displayed.

screen shot 2018-04-19 at 16 07 15

### PR DESCRIPTION
**Pull request by sashei**
resolves #278

### CODE REVIEW

**Comment by changecourse** [comment]
I'm trying to find the right branch via buddybuild to review this PR... help?

**Comment by sashei** [comment]
@changecourse `278-displaysettingsbutton`

**Comment by sashei** [comment]
@changecourse how's it looking now?

**Comment by changecourse** [comment]
tested by @nickbrandt, looks and works as expected! Thanks!

**Pull request merged**
