### PR TITLE
[WIP] point to new fxa-sync code, disconnect fully

### LINKED ISSUE #640: Start up crash due to FxAUtils
browser profile related. see Build 1940 crash logs...

### PR DESCRIPTION
**Pull request by sashei**
resolves #640

### CODE REVIEW

**Comment by sashei** [comment]
@devinreams I am curious what your experience disconnecting first from the OAuth branch would be.

I am also still seeing "No matching entries" on disconnect / reconnect so I think that bug is still present.

**Comment by sashei** [comment]
just updated from master because I saw a bug that we have already fixed.

**Comment by sashei** [comment]
...wait getting same results as @devinreams now...

**Comment by devinreams** [comment]
OK, after a quick chat we're gonna pause on this and pick it back up later. Moving on to autofill stories and will submit the 1.2 release as-is.

**Comment by sashei** [comment]
This approach doesn't work; to revisit!

**Pull request closed without merging**
