### PR TITLE
unlock automatically when device auth has become unavailable

### LINKED ISSUE #339: Automatically unlock when no device authentication available
There is the edge case when a user locks the app, and then removes all enrolled biometrics and passcodes from the device. It seems unlikely and rare and we're acknowledging that we're just going to unlock the app without any authentication.

Depends on #338

### PR DESCRIPTION
**Pull request by sashei**
resolves #339

### CODE REVIEW

**Comment by changecourse** [comment]
Agreed... I think in a future issue we may want to consider the implications of any form of auto-lock while on an unlocked device... but that's a bigger discussion.

**Comment by sashei** [comment]
you know I feel like we'd talked about making all of the autolock settings unavailable when there are no biometrics, should we just do that?

**Comment by changecourse** [comment]
Yes!

**Comment by sashei** [comment]
@changecourse @nickbrandt what about the `Lock Now` button?

**Comment by changecourse** [comment]
Probably remove as well? 

_*With the caveat*_ that we may need to revisit this once we have *OAuth* in place, to allow FxA-based locking based on using that as an authentication mechanism.

**Comment by sashei** [comment]
Wait, are we saying to _remove_ the autolock setting entirely? Or just grey it out (like a preferred browser that you don't have installed)?

**Comment by changecourse** [comment]
Ah, fair... we can disable, however, when we disable something, I'm inclined to provide description content to support what it would take to enable it, so it would be nice to have some sort of description around enabling a passcode in order to lock Lockbox.

**Comment by nickbrandt** [comment]
@sashei makes sense to me, I'll go ahead and create a follow-up issue to handle the notification dialog for once a user disables PIN/biometrics.

**Pull request merged**
