### PR TITLE
Add entry list in credential provider to replace placeholder

### LINKED ISSUE #616: Entry list
When navigating to the list of entries, display a pre-filtered list based on the `ASCredentialServiceIdentifier` (eg, `url` or `domain`). 

Important details:
- `Cancel` button cancels the autofill request entirely (calls `self.extensionContext.cancelRequest(withError: NSError(domain: ASExtensionErrorDomain, code: ASExtensionError.userCanceled.rawValue))`
- No access to settings or sorting options
- Filter still has same behavior
- Selecting an entry closes the extension, provides the complete `ASPasswordCredential` to the requesting application, and `touch`es the item so that its last-used date is reflected in `Recently Used`

Note that this story assumes that Lockbox is unlocked, the locked case is handled in #610

Requires #612

### Visual Design

**InVision**
Example App Flow for AutoFill
https://mozilla.invisionapp.com/share/BQEUSO0S2#/316626653_AutoFill_-_App_Example
Credential List*
https://mozilla.invisionapp.com/share/BQEUSO0S2#/316128721_AutoFill_-_App_Example_-_Credential_List
*The "Select a password to fill" copy would be persistent, EXCEPT when the user searches/filters the list to the No matching entries state (then we hide). After they clear the search it would reappear.

Credential List (showing how it will look when enhanced search is complete)
https://mozilla.invisionapp.com/share/BQEUSO0S2#/316128720_AutoFill_-_App_Example_-_Credential_List_-improved_Search-

Credential List - No Entries Found (none match provided domain)*
https://mozilla.invisionapp.com/share/BQEUSO0S2#/316626654_AutoFill_-_App_Example_-_Credential_List_-_No_Matches
*The "No matches found" copy would be persistent, EXCEPT when the user has entered anything in the search field (& on the No matching entries state for searching)

### LINKED ISSUE #704: Credential list not available when trying to autofill credentials via Lockbox
Build: 15e1604f4e05a
Device: iPhone 7
iOS: 12b6

Pre - conditions:
- Clean install
- Log in to Lockbox 
- Enable Autofill for Lockbox from iOS settings

Steps to reproduce:
1.  In Firefox for iOS go to facebook.com
2. Tap on the username field
3. Tap on the Autofill icon 
4. From the Autofill list, tap on Lockbox

Actual results:
- Lockbox app is opened and a prompt is displayed (Credential
 list not available yet. Please check back later)

screen shot 2018-09-12 at 5 19 15 pm

### PR DESCRIPTION
**Pull request by sashei**
resolves #616
resolves #704

### CODE REVIEW

**Comment by devinreams** [comment]
@sashei @jhugman sorry for the hassle but would you mind rebasing against `master` and changing this PR to compare accordingly? autofill is now complete and merged! 🔀

**Comment by jhugman** [comment]
Rebased against master.

**Comment by jhugman** [comment]
Still to do: 

 [ ] filtering based on credentials provided by iOS
 [ ] Learn More links are unimplemented
 [ ] Header for the entry list need to be visible.

**Comment by devinreams** [comment]
>Still to do:

Thanks, @jhugman I added that to the original description for prominent visibility.

I downloaded build 2253 on iPhone X iOS 12 and this seems to work nicely on the happy path!

- installed
- signed in
- turned on AutoFill
- browsed in Safari to reddit.com login form
- tapped "key" icon and selected "Lockbox..." from the popover list
- Lockbox list slid up from bottom
- could type to filter "reddit"
- tapped "reddit" entry and it filled form ✅

**Comment by nickbrandt** [comment]
This is working good for me as well on the happy path 👍 

Not sure if this is to be taken care of with this PR, but do notice that it is not working when the app is locked (gif below).

1 small design nit you perhaps just haven't gotten to yet – we aren't including the chevron in the credential list, since we aren't including the ability to dig into details here. 

chevron
locked

**Comment by devinreams** [comment]
>Not sure if this is to be taken care of with this PR, but do notice that it is not working when the app is locked (gif below).

Ooh yeah I just hit this too, thanks @nickbrandt. I added it to the checklist up top.

@jhugman for your info, via Slack "overnight": since iOS 12 lands on Monday I think we'll have to cut and run here pretty quick no matter what items remain, get this to internal testers by Thursday and submit that build (or major fixes) to Apple by Friday. We can talk more in standup. Thanks for your hard work on getting this done.

@sashei @nickbrandt thanks for the quick reviews, too 🏅

**Comment by devinreams** [comment]
Follow-up items added to #712 for expediency and TestFlight purposes. ✈️

**Pull request merged**
