### PR TITLE
Bootstrap file

### LINKED ISSUE #39: bootstrap.sh file

### PR DESCRIPTION
**Pull request by joeyg**
Fixes #39. This is based on the instructions for building `firefox-ios`.

### CODE REVIEW

**Comment by sashei** [comment]
@joeyg thanks for this! the bootstrap script is going to need a few more

**Comment by joeyg** [comment]
@sashei Is there other building that this script should do now that you merged in pull request #40 ?

**Comment by sashei** [comment]
@joeyg yes! if you'd like to extend it, ideally the script would also unzip the binaries.tar.gz file & let us remove the `extract-cdependencies` target in the project.

**Comment by sashei** [comment]
r-, have made another PR as the requested changes were not added.

**Comment by joeyg** [comment]
@sashei sorry I didn't have a chance to make the change. Sorry about that!

**Comment by sashei** [comment]
no worries!

**Pull request closed without merging**
